#!/usr/bin/env bash

build() {
    add_checked_modules '/drivers/net/'
}

help() {
    cat <<HELPEOF
This hook loads modules for the network devices.
For pcmcia net devices please use pcmcia hook too.
HELPEOF
}
