#!/bin/sh

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

mountpoint -q /dev || \
  mount -t devtmpfs devtmpfs /dev
mountpoint -q /proc || \
  mount -t proc proc /proc
mountpoint -q /sys || \
  mount -t sysfs sysfs /sys
mountpoint -q /sys/firmware/efi/efivars || \
  mount -t efivarfs efivarfs /sys/firmware/efi/efivars

mdev -d

echo "BusyBox Loader v0.2.1 (20230809)"
echo ""
echo "    █████████████████████████████████████"
echo "    █████████████████████████████████████"
echo "    ████ ▄▄▄▄▄ █▄▄▄ ▀ ▄█▀█ ▀▀█ ▄▄▄▄▄ ████"
echo "    ████ █   █ ██▄▀ █ █▄ ▀█▀ █ █   █ ████"
echo "    ████ █▄▄▄█ ██▀▄ ▄█ █▄▀▄▄▀█ █▄▄▄█ ████"
echo "    ████▄▄▄▄▄▄▄█ ▀▄█ ▀▄▀ █ ▀ █▄▄▄▄▄▄▄████"
echo "    ████  ▀  ▀▄▀█▄▀█▄█▄▀▄▀▀ █▀▄▀▀█▀▀▄████"
echo "    ████▀▀█▀█▀▄▀▀▄██▄▄▄▄█▀▄█ ▀▀ ▄▀▄█▀████"
echo "    ████▀ ▀▄█ ▄ ▄▄ █▀▄ ▀ ▀▀ ▄█  ▀▀▀▀ ████"
echo "    ████ █▄▀▀█▄█▀▄▄█▀▀   █▄ ▄▄▄▀ █ █ ████"
echo "    ████▀█▄██ ▄▀▄▄█ ▄██ █▀▀ ▄▄██▀▄▀▀█████"
echo "    ████  ▄▄▄█▄▄ ▀▀▀▄ ▄ ▄█▄ ██▀█▄ ▀█▄████"
echo "    ████▄▄▄▄▄█▄█▀▀▀▄▀ █ ▄ ▀█ ▄▄▄  ▄▄█████"
echo "    ████ ▄▄▄▄▄ ███▀ ▀ █ ▄    █▄█ ▄█▀█████"
echo "    ████ █   █ █ ▄▄▄▄ ▀▀▄█▀▄▄ ▄▄▄▄██ ████"
echo "    ████ █▄▄▄█ █▀▄█ ▄▄█▄▀█▄█▄▄▀ ▄▀ ▄ ████"
echo "    ████▄▄▄▄▄▄▄█▄▄████▄████▄▄█▄█▄████████"
echo "    █████████████████████████████████████"
echo "    █████████████████████████████████████"
echo ""
echo "      https://github.com/DanilKichai/bbloader"
echo ""

if [ ! -e /source ]; then
  sed -nre 's/(^|.*[ ])(source=)([^ ]*).*/\3/p' /proc/cmdline | \
    base64 -d 2>/dev/null | \
      gzip -d 1>/source 2>/dev/null
fi

if [ "$?" = 0 ]; then
  source /source
else
  exec setsid sh -c 'exec sh </dev/tty1 1>/dev/tty1 2>&1'
fi
